---
name: Task - Build Rust

on:
  workflow_dispatch:
  workflow_call:

jobs:
  rust_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: find workspace pre cache
        run: |
          find "$GITHUB_WORKSPACE" -name "Cargo.lock"

      - name: Retrieve cached build
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: find workspace post cache
        run: |
          find "$GITHUB_WORKSPACE" -name "Cargo.lock"
          echo "match all"
          echo ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          echo "match one"
          ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          echo "match from ."
          echo ${{ runner.os }}-cargo-${{ hashFiles('./**/Cargo.lock') }}

      - name: Setup rust toolchain
        if: steps.cache.outputs.cache-hit != 'true'
        run: rustup show

      - name: Setup build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm libudev-dev protobuf-compiler

      - name: Build the project
        run: |
          cargo build --release --workspace

      - uses: LouisBrunner/diff-action@v0.2.0
        with:
          old: Cargo.old.lock
          new: Cargo.lock
          mode: addition
          tolerance: better
          output: out.txt
